#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_ICO_MAIN                            1
#define DLG_SETTINGS                            1001
#define DLG_TEXT_AREA                           1002
#define DLG_PREFS                               1003
#define DLG_FIND_REPLACE                        1004
#define DLG_GOTO                                1005
#define DLG_HOT_KEYS                            1007
#define DLG_SET_ACC                             1008
#define DLG_SNIPPETS                            1009
#define DLG_DF_FORMATS                          1010
#define IDT_ACC                                 3001
#define IDC_TAB_SETTINGS                        4001
#define IDC_GRP_TEXT_ARREA_APP                  4002
#define IDC_CMD_TEXT_FONT                       4003
#define IDC_GRP_LN_APPEARANCE                   4006
#define IDC_CMD_LN_FONT                         4007
#define IDC_CHK_SHOW_LN                         4010
#define IDC_ST_TEXT_FONT                        4012
#define IDC_ST_TEXT_BCOLOR                      4013
#define IDC_ST_TEXT_FCOLOR                      4014
#define IDC_ST_LINES_FONT                       4015
#define IDC_ST_LINES_BCOLOR                     4016
#define IDC_ST_LINES_FCOLOR                     4017
#define IDC_EDT_LINES_WIDTH                     4018
#define IDC_UPD_LINES_WIDTH                     4019
#define IDC_ST_LINES_WIDTH                      4020
#define IDC_CBO_LN_ALIGNMENT                    4021
#define IDC_ST_LN_ALIGNMENT                     4022
#define IDC_GRP_TABS                            4023
#define IDC_ST_TAB_WIDTH                        4024
#define IDC_EDT_TAB_WIDTH                       4025
#define IDC_UPD_TAB_WIDTH                       4026
#define IDC_CHK_WORD_WRAP                       4027
#define IDC_GRP_BEHAVIOR                        4028
#define IDC_CHK_SINGLE_INST                     4029
#define IDC_CHK_MIN_TO_TRAY                     4030
#define IDC_ST_FIND_WHAT                        4031
#define IDC_CBO_FIND_WHAT                       4032
#define IDC_ST_REPLACE_WITH                     4033
#define IDC_CBO_REPLACE_WITH                    4034
#define IDC_CHK_MATCH_CASE                      4035
#define IDC_CHK_WHOLE_WORD                      4036
#define IDC_GRP_DIRECTION                       4037
#define IDC_OPT_UP                              4038
#define IDC_OPT_DOWN                            4039
#define IDC_CMD_FIND_NEXT                       4040
#define IDC_CMD_REPLACE                         4041
#define IDC_CMD_REPLACE_ALL                     4042
#define IDC_ST_GOTO                             4043
#define IDC_EDT_GOTO                            4044
#define IDC_GRP_OPEN_TAB                        4045
#define IDC_OPT_NEW_TAB                         4046
#define IDC_OPT_EXISTING_TAB                    4047
#define IDC_CMD_CLEAR_RECENT                    4048
#define IDC_CMD_CLEAR_SEARCH                    4049
#define IDC_GRP_NEW_SESSION                     4050
#define IDC_OPT_BLANK                           4051
#define IDC_OPT_LAST_SESSION                    4052
#define IDC_CHK_TRACK                           4053
#define IDC_CMD_DEFAULT                         4054
#define IDC_CHK_PRESERVE_POSITION               4055
#define IDC_GRP_ON_RELOAD                       4056
#define IDC_CHK_JUMP_START                      4057
#define IDC_CHK_JUMP_END                        4058
#define IDC_CHK_SHOW_BRAKES                     4059
#define IDC_CHK_SHOW_TABS                       4060
#define IDC_GRP_TEXT_MISC                       4061
#define IDC_RICH_PREVIEW                        4065
#define IDC_ST_TAB_LEN                          4066
#define IDC_EDT_TAB_SIZE                        4067
#define IDC_UPD_TAB_SIZE                        4068
#define IDC_GRP_WHITE_SPACES                    4069
#define IDC_CHK_SHOW_WS                         4070
#define IDC_CHK_SHOW_SPACES                     4071
#define IDC_ST_LEFT_BAR                         4072
#define IDC_GRP_VEW_VERSION                     4074
#define IDC_CHK_NEW_VERSION                     4075
#define IDC_CMD_NEW_VERSION                     4076
#define IDC_GRP_DEF_BROWSER                     4077
#define IDC_ST_DEF_BROWSER                      4078
#define IDC_EDT_DEF_BROWSER                     4079
#define IDC_CMD_DEF_BROWSER                     4080
#define IDC_CMD_FIND_ALL                        4081
#define IDC_ST_HK_TEXT                          4082
#define IDC_CMD_CHANGE_HK                       4083
#define IDC_ST_HK_COMMAND                       4084
#define IDC_EDT_ACC_SET                         4085
#define IDC_CMD_ADD                             4086
#define IDC_CMD_DELETE                          4087
#define IDC_ST_HK_KEYS                          4088
#define IDC_ST_ACC_SET                          4089
#define IDC_TVW_HK                              4090
#define IDC_ST_SNP_NAME                         4091
#define IDC_EDT_SNP_NAME                        4092
#define IDC_ST_SNP_TEXT                         4093
#define IDC_EDT_SNP_TEXT                        4094
#define IDC_CHK_AUTO_URL                        4095
#define IDC_OPT_CURR_FILE                       4096
#define IDC_OPT_ALL_FILES                       4097
#define IDC_GRP_DT_FORMAT                       4098
#define IDC_ST_DATE_FMT                         4099
#define IDC_ST_TIME_FMT                         4100
#define IDC_EDT_DATE_FMT                        4101
#define IDC_ST_PVW                              4102
#define IDC_ST_DATE_PVW                         4103
#define IDC_EDT_TIME_FMT                        4104
#define IDC_CMD_SHOW_DSMP                       4105
#define IDC_CMD_SHOW_TSMP                       4106
#define IDC_GRP_DT_ORDER                        4107
#define IDC_OPT_TIME_FIRST                      4108
#define IDC_OPT_DATE_FIRST                      4109
#define IDC_OPT_USE_SYS_LANG                    4110
#define IDC_OPT_USE_USER_LANG                   4111
#define IDC_GRP_SEARCH_SCOPE                    4112
#define IDM_NEW                                 6002
#define IDM_OPEN                                6009
#define IDM_SAVE                                6010
#define IDM_SAVE_AS                             6011
#define IDM_PRINT                               6012
#define IDM_EXIT                                6014
#define IDM_REFRESH                             6017
#define IDM_FIND                                6019
#define IDM_FIND_NEXT                           6020
#define IDM_REPLACE                             6021
#define IDM_GOTO                                6022
#define IDM_SAVE_ALL                            6024
#define IDM_BM_TOGGLE                           6038
#define IDM_BM_NEXT                             6039
#define IDM_TO_UPPER                            6042
#define IDM_TO_LOWER                            6043
#define IDM_UNDO_ALL                            6048
#define IDB_TAB_IML                             8001
#define IDB_IML_NORMAL                          8002
#define IDB_IML_GRAY                            8003
#define ID_CUR_HOR_SPLIT                        8004
#define IDB_IML_CLOSE                           8005
#define IDB_ACC_IML                             8006
#define IDB_IML_ASS_NORMAL                      8007
#define IDB_IML_ASS_GRAY                        8008
