#ifndef	__NUMERICCONSTANTS_H_
#define	__NUMERICCONSTANTS_H_

#define	L_MARGIN_MIN			48
#define	L_MARGIN_MAX			96
#define	L_BOOKMARK				16
#define	T_WIDTH_MIN				96
#define	T_WIDTH_MAX				204
#define	T_WIDTH_DEF				144
#define	T_SIZE_MIN				2
#define	T_SIZE_MAX				8
#define	T_SIZE_DEF				4
#define	MAX_LINE_SIZE			1024 * 32
#define	REFRESH_MENU_MIN		11000
#define	REFRESH_MENU_MAX		14000
#define	WIN_MENU_MIN			15000
#define	WIN_MENU_MAX			15255
#define	RECENT_MENU_MIN			16000
#define	LANG_MENU_MIN			17000
#define	RECENT_FILES_MAX		16
#define	BOOKMARKS_MAX			256
#define	DUMMY_TAB				-777
#define	TBNPM_BASE				WM_USER + 831
#define	TBNPM_GETACTIVEEDIT		TBNPM_BASE + 1
#define	TBNPM_SAVEONCLOSE		TBNPM_BASE + 2
#define	TBNPM_CLOSEPARAM		TBNPM_BASE + 3
#define	TBNPM_CLEARRECENT		TBNPM_BASE + 4
#define	TBNPM_OPENFROMCLINE		TBNPM_BASE + 5
#define	TBNPM_TOGGLESP			TBNPM_BASE + 6
#define	TBNPM_HSP_SIZED			TBNPM_BASE + 7
#define	TBNPM_MOVE_HSP			TBNPM_BASE + 8
#define	TBNPM_CLEAR_LIST		TBNPM_BASE + 9
#define	TBNPM_GET_TABS_CNT		TBNPM_BASE + 10
#define	TBNPM_INS_FIND_STR		TBNPM_BASE + 11
#define	TBNPM_GET_PE_BY_TAB		TBNPM_BASE + 12
#define TBNPM_ACT_BY_EDIT		TBNPM_BASE + 13
#define	TBNPM_INS_RES_STR		TBNPM_BASE + 14
#define	TBNPM_GET_ACC			TBNPM_BASE + 15
#define	TBNPM_GET_MENU_TXT		TBNPM_BASE + 16
#define	TBNPM_SELECT_ASS_TAB	TBNPM_BASE + 17
#define	TBNPM_INSERT_ASS_TAB	TBNPM_BASE + 18
#define	TBNPM_GET_ASS_TAB		TBNPM_BASE + 19
#define	TBNPM_DEL_ASS_TAB		TBNPM_BASE + 20
#define	TBNPM_GET_ACT_HANDLE	TBNPM_BASE + 21
#define	TBNPM_REMOVE_RESULTS	TBNPM_BASE + 22

#define	COLOR_B					RGB(128, 0, 255)
#define	COLOR_TABS				RGB(0, 128, 64)
#define	COLOR_SPACE				RGB(128, 0, 0)
#endif
